// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pseudomuto/sumdb (interfaces: Store,TxStore)
//
// Generated by this command:
//
//	mockgen -destination=store_test.go -package=sumdb_test . Store,TxStore
//

// Package sumdb_test is a generated GoMock package.
package sumdb_test

import (
	context "context"
	reflect "reflect"

	sumdb "github.com/pseudomuto/sumdb"
	gomock "go.uber.org/mock/gomock"
	tlog "golang.org/x/mod/sumdb/tlog"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// AddRecord mocks base method.
func (m *MockStore) AddRecord(ctx context.Context, r *sumdb.Record) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRecord", ctx, r)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddRecord indicates an expected call of AddRecord.
func (mr *MockStoreMockRecorder) AddRecord(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRecord", reflect.TypeOf((*MockStore)(nil).AddRecord), ctx, r)
}

// ReadHashes mocks base method.
func (m *MockStore) ReadHashes(ctx context.Context, indexes []int64) ([]tlog.Hash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadHashes", ctx, indexes)
	ret0, _ := ret[0].([]tlog.Hash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadHashes indicates an expected call of ReadHashes.
func (mr *MockStoreMockRecorder) ReadHashes(ctx, indexes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadHashes", reflect.TypeOf((*MockStore)(nil).ReadHashes), ctx, indexes)
}

// RecordID mocks base method.
func (m *MockStore) RecordID(ctx context.Context, path, version string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordID", ctx, path, version)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecordID indicates an expected call of RecordID.
func (mr *MockStoreMockRecorder) RecordID(ctx, path, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordID", reflect.TypeOf((*MockStore)(nil).RecordID), ctx, path, version)
}

// Records mocks base method.
func (m *MockStore) Records(ctx context.Context, id, n int64) ([]*sumdb.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Records", ctx, id, n)
	ret0, _ := ret[0].([]*sumdb.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Records indicates an expected call of Records.
func (mr *MockStoreMockRecorder) Records(ctx, id, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Records", reflect.TypeOf((*MockStore)(nil).Records), ctx, id, n)
}

// SetTreeSize mocks base method.
func (m *MockStore) SetTreeSize(ctx context.Context, size int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTreeSize", ctx, size)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTreeSize indicates an expected call of SetTreeSize.
func (mr *MockStoreMockRecorder) SetTreeSize(ctx, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTreeSize", reflect.TypeOf((*MockStore)(nil).SetTreeSize), ctx, size)
}

// TreeSize mocks base method.
func (m *MockStore) TreeSize(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TreeSize", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TreeSize indicates an expected call of TreeSize.
func (mr *MockStoreMockRecorder) TreeSize(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TreeSize", reflect.TypeOf((*MockStore)(nil).TreeSize), ctx)
}

// WriteHashes mocks base method.
func (m *MockStore) WriteHashes(ctx context.Context, indexes []int64, hashes []tlog.Hash) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteHashes", ctx, indexes, hashes)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteHashes indicates an expected call of WriteHashes.
func (mr *MockStoreMockRecorder) WriteHashes(ctx, indexes, hashes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteHashes", reflect.TypeOf((*MockStore)(nil).WriteHashes), ctx, indexes, hashes)
}

// MockTxStore is a mock of TxStore interface.
type MockTxStore struct {
	ctrl     *gomock.Controller
	recorder *MockTxStoreMockRecorder
	isgomock struct{}
}

// MockTxStoreMockRecorder is the mock recorder for MockTxStore.
type MockTxStoreMockRecorder struct {
	mock *MockTxStore
}

// NewMockTxStore creates a new mock instance.
func NewMockTxStore(ctrl *gomock.Controller) *MockTxStore {
	mock := &MockTxStore{ctrl: ctrl}
	mock.recorder = &MockTxStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxStore) EXPECT() *MockTxStoreMockRecorder {
	return m.recorder
}

// AddRecord mocks base method.
func (m *MockTxStore) AddRecord(ctx context.Context, r *sumdb.Record) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRecord", ctx, r)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddRecord indicates an expected call of AddRecord.
func (mr *MockTxStoreMockRecorder) AddRecord(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRecord", reflect.TypeOf((*MockTxStore)(nil).AddRecord), ctx, r)
}

// ReadHashes mocks base method.
func (m *MockTxStore) ReadHashes(ctx context.Context, indexes []int64) ([]tlog.Hash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadHashes", ctx, indexes)
	ret0, _ := ret[0].([]tlog.Hash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadHashes indicates an expected call of ReadHashes.
func (mr *MockTxStoreMockRecorder) ReadHashes(ctx, indexes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadHashes", reflect.TypeOf((*MockTxStore)(nil).ReadHashes), ctx, indexes)
}

// RecordID mocks base method.
func (m *MockTxStore) RecordID(ctx context.Context, path, version string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordID", ctx, path, version)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecordID indicates an expected call of RecordID.
func (mr *MockTxStoreMockRecorder) RecordID(ctx, path, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordID", reflect.TypeOf((*MockTxStore)(nil).RecordID), ctx, path, version)
}

// Records mocks base method.
func (m *MockTxStore) Records(ctx context.Context, id, n int64) ([]*sumdb.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Records", ctx, id, n)
	ret0, _ := ret[0].([]*sumdb.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Records indicates an expected call of Records.
func (mr *MockTxStoreMockRecorder) Records(ctx, id, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Records", reflect.TypeOf((*MockTxStore)(nil).Records), ctx, id, n)
}

// SetTreeSize mocks base method.
func (m *MockTxStore) SetTreeSize(ctx context.Context, size int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTreeSize", ctx, size)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTreeSize indicates an expected call of SetTreeSize.
func (mr *MockTxStoreMockRecorder) SetTreeSize(ctx, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTreeSize", reflect.TypeOf((*MockTxStore)(nil).SetTreeSize), ctx, size)
}

// TreeSize mocks base method.
func (m *MockTxStore) TreeSize(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TreeSize", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TreeSize indicates an expected call of TreeSize.
func (mr *MockTxStoreMockRecorder) TreeSize(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TreeSize", reflect.TypeOf((*MockTxStore)(nil).TreeSize), ctx)
}

// WithTx mocks base method.
func (m *MockTxStore) WithTx(ctx context.Context, fn func(sumdb.Store) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockTxStoreMockRecorder) WithTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockTxStore)(nil).WithTx), ctx, fn)
}

// WriteHashes mocks base method.
func (m *MockTxStore) WriteHashes(ctx context.Context, indexes []int64, hashes []tlog.Hash) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteHashes", ctx, indexes, hashes)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteHashes indicates an expected call of WriteHashes.
func (mr *MockTxStoreMockRecorder) WriteHashes(ctx, indexes, hashes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteHashes", reflect.TypeOf((*MockTxStore)(nil).WriteHashes), ctx, indexes, hashes)
}
